# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Déploiement en recette

on:
  push:
    branches: [ recette ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.7.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install modules
      run: yarn
    - name: Override .env
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_REACT_APP_STRATEGYAUTH: "local"
        envkey_REACT_APP_API: ${{ secrets.REACT_APP_API_RECETTE }}
        envkey_REACT_APP_PUBLIC_HOSTNAME: "https://beta.www.conseiller-numerique.gouv.fr"
        envkey_REACT_APP_COOP_HOSTNAME: "https://beta.coop.conseiller-numerique.gouv.fr/login?role=admin"
        envkey_REACT_APP_FRANCE_COMPETENCES_HOSTNAME: "https://www.francecompetences.fr/recherche/rncp/34137"
        envkey_REACT_APP_PIX_CERTIFIER_HOSTNAME: "https://pix.fr/se-certifier"
        envkey_REACT_APP_AIDE_HOSTNAME: "https://aide.conseiller-numerique.gouv.fr/fr"
        file_name: .env
    - name: Build application
      run: yarn run build
    - name: copy .htaccess
      uses: canastro/copy-file-action@master
      with:
        source: ".htaccess"
        target: "build/.htaccess"
    - name: Deploy on clever cloud
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: ${{ secrets.CLEVER_CLOUD_GIT_PORTAIL_BACKOFFICE_RECETTE }}
        BRANCH: master
        FOLDER: build
        SSH_PRIVATE_KEY: ${{ secrets.CLEVER_CLOUD_DEPLOY_PRIVATE_KEY }}
        KNOWN_HOSTS_FILE: resources/known_hosts
